coverage:
  paths:
    - src/
  
  status:
    project:
      default:
        target: 85%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 90%
        threshold: 1%

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: false