coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 3%
    patch:
      default:
        target: 80%
        threshold: 5%

  ignore:
    - "tests/"
    - "scripts/"
    - "**/__pycache__/"
    - "**/test_*.py"

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: true
