"""Tests for MCP tool schema (FastMCP-generated)."""

import pytest
from md_server.mcp.server import mcp


async def _list_tools():
    """List tools via the public FastMCP API."""
    return await mcp.list_tools()


async def _get_tool():
    """Get the convert_to_markdown tool from FastMCP."""
    tools = await _list_tools()
    return next(t for t in tools if t.name == "convert_to_markdown")


@pytest.mark.unit
class TestConvertToMarkdownSchema:
    """Tests for convert_to_markdown tool schema generated by FastMCP."""

    @pytest.mark.asyncio
    async def test_name(self):
        """Tool should be named 'convert_to_markdown'."""
        tools = await _list_tools()
        names = [t.name for t in tools]
        assert "convert_to_markdown" in names

    @pytest.mark.asyncio
    async def test_exactly_one_tool(self):
        """Should have exactly one tool registered."""
        tools = await _list_tools()
        assert len(tools) == 1

    @pytest.mark.asyncio
    async def test_has_url_property(self):
        """Tool should have url property."""
        tool = await _get_tool()
        props = tool.inputSchema.get("properties", {})
        assert "url" in props

    @pytest.mark.asyncio
    async def test_has_file_content_property(self):
        """Tool should have file_content property."""
        tool = await _get_tool()
        props = tool.inputSchema.get("properties", {})
        assert "file_content" in props

    @pytest.mark.asyncio
    async def test_has_filename_property(self):
        """Tool should have filename property."""
        tool = await _get_tool()
        props = tool.inputSchema.get("properties", {})
        assert "filename" in props

    @pytest.mark.asyncio
    async def test_render_js_not_required(self):
        """render_js should not be required."""
        tool = await _get_tool()
        required = tool.inputSchema.get("required", [])
        assert "render_js" not in required

    @pytest.mark.asyncio
    async def test_render_js_default_false(self):
        """render_js should default to False."""
        tool = await _get_tool()
        props = tool.inputSchema.get("properties", {})
        assert props["render_js"]["default"] is False

    @pytest.mark.asyncio
    async def test_description_not_empty(self):
        """Description should not be empty."""
        tool = await _get_tool()
        assert tool.description
        assert len(tool.description) > 50

    @pytest.mark.asyncio
    async def test_description_mentions_key_features(self):
        """Description should mention key features."""
        tool = await _get_tool()
        desc = tool.description.lower()
        assert "url" in desc
        assert "file" in desc
        assert "markdown" in desc

    @pytest.mark.asyncio
    async def test_description_mentions_render_js(self):
        """Description should explain render_js / JavaScript option."""
        tool = await _get_tool()
        desc = tool.description.lower()
        assert "javascript" in desc or "render_js" in desc

    @pytest.mark.asyncio
    async def test_description_mentions_formats(self):
        """Description should list supported formats."""
        tool = await _get_tool()
        desc = tool.description.lower()
        assert "pdf" in desc
        assert "docx" in desc

    @pytest.mark.asyncio
    async def test_has_output_format(self):
        """Tool should have output_format parameter."""
        tool = await _get_tool()
        props = tool.inputSchema.get("properties", {})
        assert "output_format" in props
        assert props["output_format"]["default"] == "markdown"

    @pytest.mark.asyncio
    async def test_has_include_frontmatter(self):
        """Tool should have include_frontmatter parameter."""
        tool = await _get_tool()
        props = tool.inputSchema.get("properties", {})
        assert "include_frontmatter" in props
        assert props["include_frontmatter"]["default"] is True

    @pytest.mark.asyncio
    async def test_has_max_length(self):
        """Tool should have max_length parameter."""
        tool = await _get_tool()
        props = tool.inputSchema.get("properties", {})
        assert "max_length" in props

    @pytest.mark.asyncio
    async def test_has_timeout(self):
        """Tool should have timeout parameter."""
        tool = await _get_tool()
        props = tool.inputSchema.get("properties", {})
        assert "timeout" in props

    @pytest.mark.asyncio
    async def test_has_max_tokens(self):
        """Tool should have max_tokens parameter."""
        tool = await _get_tool()
        props = tool.inputSchema.get("properties", {})
        assert "max_tokens" in props

    @pytest.mark.asyncio
    async def test_has_truncate_mode(self):
        """Tool should have truncate_mode parameter."""
        tool = await _get_tool()
        props = tool.inputSchema.get("properties", {})
        assert "truncate_mode" in props

    @pytest.mark.asyncio
    async def test_has_truncate_limit(self):
        """Tool should have truncate_limit parameter."""
        tool = await _get_tool()
        props = tool.inputSchema.get("properties", {})
        assert "truncate_limit" in props
